# Generated by Django 4.1 on 2022-08-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stayc',
            name='member',
            field=models.CharField(max_length=50),
        ),
    ]
