# Generated by Django 4.1 on 2022-08-13 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stayc', '0002_alter_stayc_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stayc',
            name='user',
        ),
    ]
