# Generated by Django 4.1 on 2022-08-13 21:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stayc', '0003_remove_stayc_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stayc',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='StayC_images'),
            preserve_default=False,
        ),
    ]
